default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: first_pancake_com_development
  username: <%= ENV["FIRST_PANCAKE_COM_DATABASE_USERNAME"] %>
  password: <%= ENV["FIRST_PANCAKE_COM_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: first_pancake_com_test
  username: <%= ENV["FIRST_PANCAKE_COM_DATABASE_USERNAME"] %>
  password: <%= ENV["FIRST_PANCAKE_COM_DATABASE_PASSWORD"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
